CREATE TABLE `ezyservices`.`account` ( `id` BIGINT(20) NOT NULL AUTO_INCREMENT , `user_name` VARCHAR(120) NOT NULL , `email` VARCHAR(150) NOT NULL , `password` TEXT NOT NULL , `phone` TEXT NOT NULL , `state` INT(1) NOT NULL DEFAULT '1' , `type` VARCHAR(20) NOT NULL , `role` VARCHAR(20) NOT NULL , `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` DATETIME on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`), UNIQUE `email` (`email`)) ENGINE = InnoDB; 

ALTER TABLE `account` CHANGE `type` `type` ENUM('MANAGER','CUSTOMER','SERVICE_PROVIDE') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 

ALTER TABLE `account` CHANGE `role` `role` ENUM('SUPER_ADMIN','USER','ADMIN') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 

ALTER TABLE `account` CHANGE `password` `password` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL; 

ALTER TABLE `account` CHANGE `phone` `phone` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL; 

ALTER TABLE `account` CHANGE `role` `role` ENUM('SUPER_ADMIN','USER','VEHICLE_WATER_SERVICING','') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 

ALTER TABLE `account` CHANGE `type` `type` ENUM('MANAGER','CUSTOMER','SERVICE_PROVIDER') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL; 